# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-04 05:36
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_quant', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('coin_name', models.CharField(blank=True, max_length=15, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Porfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
    ]
